name: Grouplet Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- scripts
- tests
- vendor

theme: jekyll-theme-guides-mbland
permalink: pretty
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Mike Bland
  url: https://mike-bland.com/

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
# logourl:
# logoalt:

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# To flatten the URL namespace so every other page is a child of the root URL:
flat_namespace: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: Life cycle
  url: life-cycle/
  internal: true
- text: Structure
  url: structure/
  internal: true
- text: Processes and artifacts
  url: processes-and-artifacts/
  internal: true
- text: Education and advocacy
  url: education-and-advocacy/
  internal: true
- text: Intergrouplets
  url: intergrouplets/
  internal: true
- text: Origin story
  url: origin-story/
  internal: true

repos:
- name: Grouplet Guide
  description: Main repository
  url: https://github.com/mbland/grouplet-playbook
- name: Guides Template
  description: Template repository
  url: https://github.com/mbland/guides-template
- name: jekyll-theme-guides-mbland
  description: Theme repository
  url: https://github.com/mbland/jekyll-theme-guides-mbland

back_link:
  url: https://mike-bland.com/
  text: "Back to Mike Bland's site"

#google_analytics_ua:

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
